### ISSUE TITLE
Script does not allow Copy / Paste of client _id and client_secret

### ISSUE THREAD

**Issue by pjgrun** [MyTeslaMate/generate-fleet-tokens#2]
Script does not allow Copy / Paste of client _id and client_secret.

**Comment by jlestel** [comment]
Hi there 👋

Thanks a lot for the feedback!

You're absolutely right — the script was using Read-Host -AsSecureString, which can prevent copy/paste in some terminal environments. We've just updated the script to use standard input instead, making it easier to paste your client_id and client_secret.

Feel free to pull the latest version — and let us know if you run into anything else!

Thanks again for pointing this out 🙌

**Comment by pjgrun** [comment]
Thank you! Tested and works now. 
Unfortunately still not able to complete the process due to issue reported in #3 
Thank you.
